#!/usr/bin/env bash

sudo pacman -S --noconfirm --needed gimp
sudo pacman -S --noconfirm --needed hyprcursor
sudo pacman -S --noconfirm --needed hyprgraphics
sudo pacman -S --noconfirm --needed hypridle
sudo pacman -S --noconfirm --needed hyprland
sudo pacman -S --noconfirm --needed hyprlang
sudo pacman -S --noconfirm --needed hyprlock
sudo pacman -S --noconfirm --needed hyprpaper
sudo pacman -S --noconfirm --needed hyprshot
sudo pacman -S --noconfirm --needed kitty
sudo pacman -S --noconfirm --needed man-db
sudo pacman -S --noconfirm --needed nano
sudo pacman -S --noconfirm --needed neovim
sudo pacman -S --noconfirm --needed obsidian
sudo pacman -S --noconfirm --needed pacman-contrib
sudo pacman -S --noconfirm --needed pavucontrol
sudo pacman -S --noconfirm --needed pipewire-alsa
sudo pacman -S --noconfirm --needed pipewire-pulse
sudo pacman -S --noconfirm --needed pipewire-audio
sudo pacman -S --noconfirm --needed pipewire-jack
sudo pacman -S --noconfirm --needed playerctl
sudo pacman -S --noconfirm --needed qjackctl
sudo pacman -S --noconfirm --needed waypaper
sudo pacman -S --noconfirm --needed wev
sudo pacman -S --noconfirm --needed yay
sudo pacman -S --noconfirm --needed yay-debug
sudo pacman -S --noconfirm --needed bash-completion
sudo pacman -S --noconfirm --needed ghostty
sudo pacman -S --noconfirm --needed btop
sudo pacman -S --noconfirm --needed neofetch
sudo pacman -S --noconfirm --needed stylua
sudo pacman -S --noconfirm --needed cmake
sudo pacman -S --noconfirm --needed chromium
sudo pacman -S --noconfirm --needed hyprpm

# yay packages
yay -S --noconfirm --needed brave-bin
